/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ProgramsImport } from './routes/programs'
import { Route as OnlineTestsImport } from './routes/online-tests'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ProgramsRoute = ProgramsImport.update({
  path: '/programs',
  getParentRoute: () => rootRoute,
} as any)

const OnlineTestsRoute = OnlineTestsImport.update({
  path: '/online-tests',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/online-tests': {
      id: '/online-tests'
      path: '/online-tests'
      fullPath: '/online-tests'
      preLoaderRoute: typeof OnlineTestsImport
      parentRoute: typeof rootRoute
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  OnlineTestsRoute,
  ProgramsRoute,
})

/* prettier-ignore-end */
